#!/bin/bash

declare -a diversions=(
  "/usr/lib/x86_64-linux-gnu/libGLX.so.0"
  "/usr/lib/x86_64-linux-gnu/libGLX.so.0.0.0"
)

diversion_added_version=1.1.0-4
this_version=1.1.0-4

if
  test "$1" = install ||
  dpkg --compare-versions "$2" lt "$diversion_added_version" ||
  dpkg --compare-versions "$this_version" lt "$2"
then
  for diversion in "${diversions[@]}"
  do
    dpkg-divert --package libglvnd --add --rename \
      --divert ${diversion}.old ${diversion}
  done
fi

#DEBHELPER#
exit 0